-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 19:34:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dailyquestdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dailyquestdb` ;

-- -----------------------------------------------------
-- Schema dailyquestdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dailyquestdb` DEFAULT CHARACTER SET utf8 ;
USE `dailyquestdb` ;

-- -----------------------------------------------------
-- Table `dailyquestdb`.`users_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dailyquestdb`.`users_tbl` ;

CREATE TABLE IF NOT EXISTS `dailyquestdb`.`users_tbl` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(50) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `user_password` VARCHAR(255) NULL,
  `user_address` VARCHAR(255) NULL,
  `user_contact` VARCHAR(45) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `userUID_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dailyquestdb`.`quest_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dailyquestdb`.`quest_tbl` ;

CREATE TABLE IF NOT EXISTS `dailyquestdb`.`quest_tbl` (
  `quest_id` INT NOT NULL AUTO_INCREMENT,
  `quest_provider_fk_id` INT NOT NULL,
  `quest_name` VARCHAR(50) NOT NULL,
  `quest_description` LONGTEXT NOT NULL,
  `quest_date` VARCHAR(50) NOT NULL,
  `quest_location` VARCHAR(100) NOT NULL,
  `quest_timespan` VARCHAR(20) NOT NULL,
  `quest_bounty` FLOAT NOT NULL,
  `questStatus` ENUM('active', 'inactive') NULL DEFAULT 'active',
  `quest_difficulty` ENUM('Easy', 'Medium', 'Hard') NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`quest_id`),
  UNIQUE INDEX `questID_UNIQUE` (`quest_id` ASC) VISIBLE,
  CONSTRAINT `quest_provider_fk_id`
    FOREIGN KEY (`quest_provider_fk_id`)
    REFERENCES `dailyquestdb`.`users_tbl` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dailyquestdb`.`quest_session_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dailyquestdb`.`quest_session_tbl` ;

CREATE TABLE IF NOT EXISTS `dailyquestdb`.`quest_session_tbl` (
  `quest_session_id` INT NOT NULL,
  `quest_id` INT NOT NULL,
  `quest_seeker_id` INT NOT NULL,
  `quest_status` ENUM('pending', 'accepted', 'cancelled', 'done') NOT NULL,
  `createAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`quest_session_id`),
  INDEX `quest_fk_id_idx` (`quest_id` ASC) VISIBLE,
  INDEX `quest_seeker_id_idx` (`quest_seeker_id` ASC) VISIBLE,
  CONSTRAINT `quest_fk_id`
    FOREIGN KEY (`quest_id`)
    REFERENCES `dailyquestdb`.`quest_tbl` (`quest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quest_seeker_id`
    FOREIGN KEY (`quest_seeker_id`)
    REFERENCES `dailyquestdb`.`users_tbl` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
